identifier = "com.example.object-detection.conveyor-application-barcodes"
app_version = "1.0.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3 python3-pip libzbar0 libzbar-dev" },
    { type = "COPY", source = "requirements.txt", target = "requirements.txt" },
    { type = "RUN", command = "pip3 install -r /app/requirements.txt --break-system-packages"},
]

prepare_build_container = []

build_steps = []

depthai_models = { yaml_path = "./depthai_models" }

entrypoint = ["bash", "-c", "python3 -u /app/main.py"]