identifier = "com.example.face-detection.age-gender"
entrypoint = ["bash", "-c", "/usr/bin/runsvdir -P /etc/service"]
app_version = "1.0.2"
assign_frontend_port = true

prepare_container = [
    { type = "COPY", source = "./requirements.txt", target = "./requirements.txt" },
    { type = "RUN", command = "python3.12 -m pip install -r /app/requirements.txt --break-system-packages"}
]

build_steps = [
    "mkdir -p /etc/service/backend",
    "cp /app/backend-run.sh /etc/service/backend/run",
    "chmod +x /etc/service/backend/run",
]

depthai_models = { yaml_path = "./depthai_models" }

[base_image]
api_url = "https://registry-1.docker.io"
service = "registry.docker.io"
oauth_url = "https://auth.docker.io/token"
auth_type = "repository"
auth_name = "luxonis/oakapp-base"
image_name = "luxonis/oakapp-base"
image_tag = "1.2.6"
