identifier = "com.example.integrations.foxglove"
app_version = "1.0.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3-pip libgl1" },
    { type = "COPY", source = "requirements.txt", target = "requirements.txt" },
    { type = "RUN", command = "pip3 install -r /app/requirements.txt --break-system-packages --default-timeout=100" }, # increase in timeout because of open3d
]

prepare_build_container = []

build_steps = []

entrypoint = ["bash", "-c", "python3 -u /app/main.py"]
