identifier = "ros.driver.spatial_bb_example"
app_version = "1.0.0"

prepare_container = [
    { type = "COPY", source = "resolv.conf", target = "/etc/resolv.conf" },
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y ros-kilted-depthai-ros"},
]

prepare_build_container = [

]

build_steps = [
]

entrypoint = ["bash", "-c", "source /opt/ros/kilted/setup.bash && ros2 launch dephtai_filters spatial_bb.launch.py"]

[base_image]
api_url = "https://registry-1.docker.io" 
service = "registry.docker.io" 
oauth_url = "https://auth.docker.io/token"
auth_type = "repository" 
auth_name = "library/ros"
image_name = "library/ros"
image_tag = "kilted-ros-base"
